baseURL = "https://v31dt.github.io/"
locale = "en-gb"
title = "Robert Akhmerov | v31dt"
theme = "archie"
copyright = "© Robert Akhmerov"
cacheDir = "/tmp/hugo_cache/profnet"

pygmentsStyle = "monokai"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

[params]
mode = "auto"
useCDN = false
subtitle = "Cybersecurity student and Certified Ethical Hacker focused on web and mobile penetration testing, malware analysis, and security automation."
customCSS = ["css/local-palette.css"]
mainSections = ["posts"]

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/v31dt"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/robert-akhmerov-7166a72a2/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
name = "All posts"
url = "/posts/"
weight = 3

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 5
